server:
  port: 8001

security:
  oauth2:
    client:
      client-secret: 123456
      client-id: gateway
    resource:
      jwt:
        key-uri: http://localhost:9090/oauth/token_key
spring:
  application:
    name: order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8720
      log:
        dir: order/sentinel-log
logging:
  level:
    com.jc.spring.order: debug


sentinel:
  nacos:
    server-addr: 10.1.21.137:8848
    dataId: order-flow-rules
    groupId: SENTINEL_GROUP
    username: nacos
    password: nacos