server:
  port: 8001
#  servlet:
#    context-path: /order

security:
  oauth2:
    client:
      client-secret: 123456
      client-id: gateway
    resource:
      jwt:
        key-uri: http://localhost:9090/ouath