server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: oauth2
          uri: http://localhost:9090
          predicates:
           - Path=/token/**
          filters:
            - StripPrefix=1  # 取消oauth2作为转发前缀
        - id: order
          uri: http://localhost:8001
          predicates:
            - Path=/order/**